Design and implementation of scenario tree
smokinmirror/raocp-toolbox pull request #3
Opened 2022-03-04 01:52 UTC by alphaville

## About 

Design and implementation of scenario tree. @Gczmy and @smokinmirror you are invited to participate. I have written a few unit tests (see [TDD](https://en.wikipedia.org/wiki/Test-driven_development)).

Note: do not merge! This is work in progress!

## Issues

- Addresses #1

2022-03-09 15:36 UTC, alphaville commented
@Gczmy This is almost ready now. We just need to (i) implement at least one more test, (ii) document all methods. @Gczmy and @smokinmirror I have requested your review on this. Let us try to get this done soon, merge this branch and close #1.

2022-03-09 16:26 UTC, Gczmy approved these changes
All test pass.

2022-03-10 21:58 UTC, Gczmy approved these changes
All tests pass.

2022-03-11 16:48 UTC, smokinmirror requested changes
@Gczmy couple of tweaks and a unit test you should be able to implement

2022-03-11 16:48 UTC, ruairimoran commented on ci/script.sh
> +    # --- install opengen
opengen ?

2022-03-11 16:48 UTC, ruairimoran commented on raocp/core/scenario_tree.py
> +        :param stages:
bulk out docs

2022-03-11 16:48 UTC, ruairimoran commented on raocp/core/scenario_tree.py
> +        :param stages:
bulk out docs

2022-03-11 16:48 UTC, ruairimoran commented on raocp/core/scenario_tree.py
> +        Returns `None` if no data are stored at the given node
move line to `get_data_at_node` doc above

2022-03-11 16:48 UTC, ruairimoran commented on raocp/core/scenario_tree.py
> +        return len(self.__ancestors)
double check

2022-03-11 16:48 UTC, ruairimoran commented on raocp/core/scenario_tree.py
> +        return len(self.__ancestors)
may need +1 for root node

2022-03-11 16:48 UTC, ruairimoran commented on raocp/core/scenario_tree.py
> +        :param stopping_time: stopping time, which much be no larger than the number of stages [default: None]
much -> must

2022-03-11 16:48 UTC, ruairimoran commented on tests/test_scenario_tree.py
> +import unittest
failure test for when `tau > N`

2022-03-14 12:28 UTC, smokinmirror commented on ci/script.sh
> +    # --- install opengen
changed to `raocp-toolbox`

2022-03-14 12:43 UTC, smokinmirror commented on raocp/core/scenario_tree.py
> +        :param stages:
done

2022-03-14 12:45 UTC, smokinmirror commented on raocp/core/scenario_tree.py
> +        Returns `None` if no data are stored at the given node
done

2022-03-14 12:47 UTC, smokinmirror commented on raocp/core/scenario_tree.py
> +        return len(self.__ancestors)
don't need to. root node is given ancestor -1

2022-03-14 12:47 UTC, smokinmirror commented on raocp/core/scenario_tree.py
> +        :param stopping_time: stopping time, which much be no larger than the number of stages [default: None]
done

2022-03-14 13:10 UTC, smokinmirror commented on tests/test_scenario_tree.py
> +import unittest
done

2022-03-14 13:15 UTC, smokinmirror approved these changes
on to the next thing

2022-03-14 13:46 UTC, merged