The implementation of projections on linear spaces.
smokinmirror/raocp-toolbox pull request #5
Opened 2022-03-07 18:23 UTC by Gczmy

### **About**
----
The implementation of projections on linear spaces.

This is work in progress.

2022-03-07 18:28 UTC, alphaville requested changes
I don't see any code related to the computation of projections on linear spaces...

2022-03-07 18:28 UTC, alphaville commented on main.py
> +<<<<<<< HEAD
resolve the conflicts

2022-03-07 18:28 UTC, alphaville commented on raocp/core/scenario_tree.py
> +<<<<<<< HEAD
this is a conflict - please resolve it

2022-03-07 18:57 UTC, Gczmy commented
> I don't see any code related to the computation of projections on linear spaces...
I have uplode the "kernel.py" into folder "playground" and resove these conflicts to keep same with the branch "main".

2022-03-08 19:09 UTC, alphaville approved these changes

2022-03-11 10:56 UTC, smokinmirror approved these changes

2022-03-13 17:39 UTC, merged